package com.android.solvit.shared.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF0099FF)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFE5F3FF)
val OnPrimaryContainer = Color(0xFF001E2F)
val Secondary = Color(0xFF28A745)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE5F6E8)
val OnSecondaryContainer = Color(0xFF00210B)
val Error = Color(0xFFEC5865)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFDE8E8)
val OnErrorContainer = Color(0xFF410002)
val Background = Color(0xFFFFFFFF)
val OnBackground = Color(0xFF1A1C1E)
val Surface = Color(0xFFFFFFFF)
val OnSurface = Color(0xFF1A1C1E)
val SurfaceVariant = Color(0xFFE5E5E5)
val OnSurfaceVariant = Color(0xFF44474A)
val Available = Color(0xFF28A745)
val Unavailable = Color(0xFFDC3545)
val Busy = Color(0xFFFFC107)
val LightOrange = Color(0xFFFFF3E0)
val LightBlue = Color(0xFFE3F2FD)
val LightRed = Color(0xFFFFEBEE)