package com.android.solvit.shared.model.packages

import android.util.Log
import com.google.android.gms.tasks.Task
import com.google.firebase.firestore.DocumentSnapshot
import com.google.firebase.firestore.FirebaseFirestore

/**
 * Firestore-based implementation of the `PackageProposalRepository` interface. Manages CRUD
 * operations for package proposals using Firebase Firestore.
 *
 * @property db The Firebase Firestore database instance.
 */
class PackageProposalRepositoryFirestore(private val db: FirebaseFirestore) :
    PackageProposalRepository {

  private val collectionPath = "packages"

  /**
   * Generates a new unique identifier for a package proposal.
   *
   * @return A unique document ID generated by Firestore.
   */
  override fun getNewUid(): String {
    return db.collection(collectionPath).document().id
  }

  /**
   * Initializes the repository by performing setup tasks if necessary.
   *
   * @param onSuccess Callback invoked when initialization succeeds.
   */
  override fun init(onSuccess: () -> Unit) {
    onSuccess()
  }

  /**
   * Retrieves all package proposals from the Firestore collection.
   *
   * @param onSuccess Callback invoked with a list of package proposals upon successful retrieval.
   * @param onFailure Callback invoked with an exception if retrieval fails.
   */
  override fun getPackageProposal(
      onSuccess: (List<PackageProposal>) -> Unit,
      onFailure: (Exception) -> Unit
  ) {
    Log.d("PackageProposalRepositoryFirestore", "getPackageProposal")
    db.collection(collectionPath).get().addOnCompleteListener { task ->
      if (task.isSuccessful) {
        val proposal =
            task.result?.mapNotNull { document -> documentToPackageProposal(document) }
                ?: emptyList()
        onSuccess(proposal)
      } else {
        task.exception?.let { e ->
          Log.e("PackageProposalRepositoryFirestore", "Error getting documents", e)
          onFailure(e)
        }
      }
    }
  }

  /**
   * Adds a new package proposal to the Firestore collection.
   *
   * @param proposal The package proposal to be added.
   * @param onSuccess Callback invoked when the proposal is successfully added.
   * @param onFailure Callback invoked with an exception if adding the proposal fails.
   */
  override fun addPackageProposal(
      proposal: PackageProposal,
      onSuccess: () -> Unit,
      onFailure: (Exception) -> Unit
  ) {
    performFirestoreOperation(
        db.collection(collectionPath).document(proposal.uid).set(proposal), onSuccess, onFailure)
  }

  /**
   * Updates an existing package proposal in the Firestore collection.
   *
   * @param proposal The updated package proposal.
   * @param onSuccess Callback invoked when the proposal is successfully updated.
   * @param onFailure Callback invoked with an exception if updating the proposal fails.
   */
  override fun updatePackageProposal(
      proposal: PackageProposal,
      onSuccess: () -> Unit,
      onFailure: (Exception) -> Unit
  ) {
    performFirestoreOperation(
        db.collection(collectionPath).document(proposal.uid).set(proposal), onSuccess, onFailure)
  }

  /**
   * Deletes a package proposal from the Firestore collection based on its unique ID.
   *
   * @param id The unique identifier of the package proposal to be deleted.
   * @param onSuccess Callback invoked when the proposal is successfully deleted.
   * @param onFailure Callback invoked with an exception if deletion fails.
   */
  override fun deletePackageProposal(
      id: String,
      onSuccess: () -> Unit,
      onFailure: (Exception) -> Unit
  ) {
    performFirestoreOperation(
        db.collection(collectionPath).document(id).delete(), onSuccess, onFailure)
  }

  /**
   * Performs a Firestore operation and handles its result.
   *
   * @param task The Firestore task to be performed.
   * @param onSuccess Callback invoked when the task succeeds.
   * @param onFailure Callback invoked with an exception if the task fails.
   */
  private fun performFirestoreOperation(
      task: Task<Void>,
      onSuccess: () -> Unit,
      onFailure: (Exception) -> Unit
  ) {
    task.addOnCompleteListener { result ->
      if (result.isSuccessful) {
        onSuccess()
      } else {
        result.exception?.let { e ->
          Log.e("PackageProposalRepositoryFirestore", "Error performing Firestore operation", e)
          onFailure(e)
        }
      }
    }
  }

  /**
   * Converts a Firestore document snapshot into a `PackageProposal` object.
   *
   * @param document The Firestore document snapshot.
   * @return The corresponding `PackageProposal` object or `null` if conversion fails.
   */
  fun documentToPackageProposal(document: DocumentSnapshot): PackageProposal? {
    return try {
      val uid = document.id
      val title = document.getString("title") ?: return null
      val packageNumber = document.getDouble("packageNumber") ?: return null
      val providerId = document.getString("providerId") ?: return null
      val description = document.getString("description") ?: return null
      val price = document.getDouble("price") ?: return null
      val bulletPoints = document.get("bulletPoints") as? List<String> ?: emptyList()

      PackageProposal(
          uid = uid,
          title = title,
          packageNumber = packageNumber,
          providerId = providerId,
          description = description,
          price = price,
          bulletPoints = bulletPoints)
    } catch (e: Exception) {
      Log.e("PackageProposalRepositoryFirestore", "Error converting document to PackageProposal", e)
      null
    }
  }
}
