name: CI - Test Runner

# Run the workflow when commits are pushed on main or when a PR is modified
on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    name: CI
    # Execute the CI on the course's runners
    runs-on: ubuntu-latest

    steps:
      # First step : Checkout the repository on the runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of Sonar analysis (if we use Sonar Later)
      
      # This step removes the current gradle cache to avoid any caching issues
      - name: Remove current gradle cache
        run: rm -rf ~/.gradle

      # Kernel-based Virtual Machine (KVM) is an open source virtualization technology built into Linux. Enabling it allows the Android emulator to run faster.
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # Caching is a very useful part of a CI, as a workflow is executed in a clean environment every time,
      # this means that one would need to re-download and re-process gradle files for every run. Which is very time consuming.
      #
      # To avoid that, we cache the the gradle folder to reuse it later.
      - name: Retrieve gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Load google-services.json and local.properties from the secrets
      - name: Decode secrets
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json
          echo "$LOCAL_PROPERTIES" | base64 --decode > ./local.properties

      # Decode the keystore
      - name: Decode release keystore
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          echo "$RELEASE_KEYSTORE" | base64 --decode > ./release-key.jks

      # Set up the signing configuration in the Gradle build
      - name: Setup signing configuration
        run: |
          echo "RELEASE_STORE_FILE=app/release-key.jks" >> local.properties
          echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> local.properties
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> local.properties
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> local.properties

      - name : Setup Google AI key
        run: |
          echo "GOOGLE_AI_API_KEY=${{ secrets.GOOGLE_AI_API_KEY }}" >> local.properties

      - name : Set Open AI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> local.properties

      # Cache the Emulator, if the cache does not hit, create the emulator
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-34

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: >-
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -no-snapshot
            -no-snapshot-save
            -camera-back none
            -memory 2048
            -skin 1080x1920
            -ranchu
            -netfast
            -accel on
            -qemu -m 2048
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Start Firebase emulators
        run: |
          nohup firebase emulators:start --only auth,firestore,database,storage & sleep 10

      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./gradlew

      # Check formatting
      - name: KTFmt Check
        run: |
          ./gradlew ktfmtCheck

      # This step runs gradle commands to build the application
      - name: Assemble
        run: |
          # To run the CI with debug information, add --info
          ./gradlew assemble lint --parallel --build-cache

      # Run Unit tests
      - name: Run tests
        run: |
          # To run the CI with debug information, add --info
          ./gradlew check --parallel --build-cache

      # Run instrumentation tests on the emulator
      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          avd-name: github
          force-avd-creation: true
          emulator-options: >-
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -no-snapshot
            -no-snapshot-save
            -camera-back none
            -memory 2048
            -skin 1080x1920
            -ranchu
            -netfast
            -accel on
            -qemu -m 2048
          disable-animations: true
          script: |
            adb wait-for-device
            echo "Waiting for system boot..."
            start_time=`date +%s`; while true; do boot_status=`adb shell getprop sys.boot_completed 2>/dev/null || echo error`; current_time=`date +%s`; elapsed=$((current_time - start_time)); if [ "$boot_status" = "1" ]; then echo "System boot completed"; break; fi; if [ $elapsed -gt 300 ]; then echo "ERROR: Timeout waiting for system boot"; exit 1; fi; sleep 5; done
            
            echo "Waiting for package manager..."
            start_time=`date +%s`; while true; do pm_count=`adb shell pm path android 2>/dev/null | grep -c package: || echo 0`; current_time=`date +%s`; elapsed=$((current_time - start_time)); if [ "$pm_count" -gt "0" ]; then echo "Package manager is ready"; break; fi; if [ $elapsed -gt 120 ]; then echo "ERROR: Timeout waiting for package manager"; exit 1; fi; sleep 5; done
            
            echo "Optimizing emulator settings..."
            adb shell settings put global window_animation_scale 0 || true
            adb shell settings put global transition_animation_scale 0 || true
            adb shell settings put global animator_duration_scale 0 || true
            
            echo "Running instrumentation tests..."
            adb logcat -c;
            adb logcat > logcat.txt & LOGCAT_PID=$!;
            ./gradlew connectedCheck -Pandroid.testInstrumentationRunnerArguments.timeout_msec=60000 -Pandroid.testInstrumentationRunnerArguments.numRetries=2 --no-daemon --max-workers=2 -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dkotlin.incremental=false;
            kill $LOGCAT_PID || true;

      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            app/build/reports/androidTests/connected/
            app/build/outputs/androidTest-results/
            app/build/reports/tests/
            app/build/test-results/

      # Upload logcat on failure
      - name: Upload logcat output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logcat
          path: logcat.txt

      # Upload heap dump on OOM
      - name: Upload heap dump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: heap-dump
          path: '*.hprof'

      # Cache the build outputs
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            app/build/intermediates
            app/build/tmp
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      # This step generates the coverage report which will be uploaded to sonar
      - name: Generate Coverage Report
        run: |
          ./gradlew jacocoTestReport

      # Upload coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: Coverage report
          path: app/build/reports/jacoco/jacocoTestReport

      # Upload the various reports to sonar
      - name: Upload report to SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION : ${{ secrets.SONAR_ORGANIZATION}}
          SONAR_PROJECT_KEY : ${{ secrets.SONAR_PROJECT_KEY}}
        run: ./gradlew sonar --parallel --build-cache
